name: Test workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: "Test job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Hello"
        run: "python -c \"print('Hello, World')\""
      
      
